-- return {
--   {
--     "catppuccin/nvim",
--     name = "catppuccin",
--     priority = 1000,
--     config = function()
--       require("catppuccin").setup({
--         flavour = "macchiato",
--         integrations = {
--           neogit = true,
--           which_key = true,
--         },
--       })
--       vim.cmd.colorscheme("catppuccin")
--     end,
--   },
-- }
